### ISSUE TITLE
Bear for Dart

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala-bears#105]
I like Dart somehow since last time I stumbled upon it, looks like a python for javascript or so :)
https://www.dartlang.org/

**Comment by sils1297** [comment]
is there a linter we can use?

**Comment by nishant-mor** [comment]
@sils1297 https://github.com/dart-lang/linter

**Comment by Adrianzatreanu** [comment]
I would like to get assigned for this :)

**Comment by AbdealiJK** [comment]
https://github.com/jonkirkman/sublime-dart-linter/blob/master/dartlint.py is a good reference

**Comment by AbdealiJK** [comment]
I'd suggest `dartanalyzer` (https://github.com/dart-lang/sdk/tree/master/pkg/analyzer) as it comes in built with the dart sdk. Also, other plugin writers seem to prefer it.
