### ISSUE TITLE
JSHintBearTest not working properly.

### ISSUE THREAD

**Issue by ravinimmi** [coala-analyzer/coala-bears#108]
Tests are passing even if i interchange valid and invalid files https://github.com/coala-analyzer/coala-bears/blob/master/tests/js/JSHintBearTest.py#L25 .

**Comment by AbdealiJK** [comment]
Just tried it locally, if I move test_file1 and test_file2 to valid_files
and it failed.
Could you explain steps to reproduce in more details ?
