### ISSUE TITLE
PerlCritic: No arg named config

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala-bears#109]
PerlCritic gives an exception when using a config - It says no arg named `--config` exists.

Our test for config files is bad. hence we didnt catch this.

We need to remove this config

**Comment by AbdealiJK** [comment]
@sudheesh001 (just checked, seems like you wrote that part) - Is the config parameter actually there ? Am I missing something ? My `perlcritic` doesn't have it

**Comment by ravinimmi** [comment]
I think it should be replaced with '--profile' instead of '--config' http://search.cpan.org/~thaljef/Perl-Critic-1.126/bin/perlcritic
