### ISSUE TITLE
SwiftLint for Swift

### ISSUE THREAD

**Issue by nishant-mor** [coala-analyzer/coala-bears#11]
we can use https://github.com/realm/SwiftLint

**Comment by Adrianzatreanu** [comment]
You want a linter bear for swift?

**Comment by sils1297** [comment]
Yeah why not?

**Comment by Adrianzatreanu** [comment]
It wasnt a matter of why, it was a matter of : "is this what you asked?" as this issue was described pretty vague, and i wanted to ask to be sure :)

**Comment by Adrianzatreanu** [comment]
Well id be glad to help if you'd let me then :)

**Comment by sudheesh001** [comment]
Assigned it to you @Adrianzatreanu

**Comment by Adrianzatreanu** [comment]
I was planning on writing this on linux. I didnt expect it not to be able to be installed on it ;p seems all the install methods are for mac os only.. my bad ;( if this is only for mac osx users to fix, please unassign me and sorry :)

**Comment by sils1297** [comment]
this is not doable on linux? Do we want it?

**Comment by AbdealiJK** [comment]
As @sils1297 mentioned in https://github.com/coala-analyzer/coala-bears/issues/336 we could use https://github.com/sleekbyte/tailor if swiftlint is complicated.

**Comment by AbdealiJK** [comment]
@SanketDG why is this blocked ? Please give a reason if you add that label

**Comment by SanketDG** [comment]
@AbdealiJK sorry about that, but we had a discussion on https://github.com/coala-analyzer/coala-bears/pull/177. Looks like `swift` is not ready for `linux`. `tailor` uses java to parse code, so I think that can be used.

**Comment by sils1297** [comment]
@arafsheikh time to look into this? Having a linter for swift using tailor would be neat and easy.

This is not blocked as tailor can be used.

**Comment by arafsheikh** [comment]
I'll look into it first thing tomorrow morning.
