### ISSUE TITLE
Reduce requests timeout for InvalidLinkBear.

### ISSUE THREAD

**Issue by ravinimmi** [coala-analyzer/coala-bears#111]
For this link http://coalaisthebest.com, test is always failing for me.

**Comment by Makman2** [comment]
Is there already a default timeout for `InvalidLinkBear`?

**Comment by sils1297** [comment]
If there is it's inherited, we don't set one. We could provide it as a
setting.

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-02-25 15:17 GMT+01:00 Mischa Krüger <notifications@github.com>:

**Comment by SanketDG** [comment]
What should be the ideal timeout set for the requests?
Since `py.test` times out in > 35s, should it be 35s. I am not sure of the right thing to do here.

**Comment by ravinimmi** [comment]
35s is for all the tests right? I would suggest < 2s for each request.

**Comment by Makman2** [comment]
I think 2s is a bit short, would suggest 5s. Sometimes there are slow servers or your own infrastructure hangs a bit :)
And yeah like @sils1297 suggested we should use a setting for that, so if users encounter timeout problems they can manually set it. :+1:

**Comment by sils1297** [comment]
A timeout of several seconds does not sound acceptable to me.

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-02-25 15:43 GMT+01:00 Mischa Krüger <notifications@github.com>:

**Comment by Makman2** [comment]
Alright due to gitter I'll also vote for 2sec :+1:

**Comment by SanketDG** [comment]
@ravinimmi Could you fetch https://github.com/SanketDG/coala-bears/commit/5bdaa369275f7a8679673bcbd052a49f83eb0e08 and run the tests and see if its okay right now?

**Comment by ravinimmi** [comment]
@SanketDG It is still failing for me. Are all the tests passing on your machine?

**Comment by ravinimmi** [comment]
@SanketDG The problem is only on my machine I think. timeout isn't working for me. Maybe @sils1297 could check.

**Comment by AbdealiJK** [comment]
Which OS and system do you have ? Also what's your internet speed ? Are you
inside a proxy ? Do you use some sort of VPN or are you inside a vagrant or
virtualbox ?

**Comment by Makman2** [comment]
@AbdealiJK His timeout-parameter is not working it seems. For me tests do succeed and the timeout is working properly. I think this is a local problem on his machine^^ Though a timeout is needed anyway :D

**Comment by AbdealiJK** [comment]
Then which version of requests and python are you using @ravinimmi  ?

Also, just a note - the 35 seconds is for each test in pytest. (The DbusTest takes about 15 seconds on some computers) And we increased it to 35 as appveyor was timing out a while back

**Comment by ravinimmi** [comment]
@AbdealiJK I am on Mac 10.11.3.
- Internet Speed : 16Mbps
- No proxy, vagrant or virtualbox
- Python 3.5.1
- pip 8.0.2
- requests==2.9.1

**Comment by AbdealiJK** [comment]
Hm - I seem to be using the exact same stack as you except I use Ubuntu.

Maybe this a Mac specific thing ? Can anyone with a Mac check it out ?

**Comment by ravinimmi** [comment]
@SanketDG @AbdealiJK Ok, I got the problem on my machine. Actually the DNS lookup was taking a lot of time(I think requests doesn't take this into account. Maybe it is a safe thing?). I was using the default DNS server. After changing to google's DNS server 8.8.8.8 it worked. All the tests are passing :)

**Comment by SanketDG** [comment]
@ravinimmi Hey congrats, but I still think a timeout of 1s is necessary.

**Comment by ravinimmi** [comment]
@SanketDG yup, its necessary.
