### ISSUE TITLE
autogenerate JSHint config from settings

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala-bears#115]
difficulty/medium ?

**Comment by AbdealiJK** [comment]
This is actually pretty easy - we have the `config_file` function so we just need to figure out a list of jshint configs and map them appropriately (Check markdown bear - does something similar)

**Comment by sils1297** [comment]
yeah the only problem here is that we need to generate XML or something
like that but I agree that it's pretty doable. But I think jshint is
important. We should also file bugs for other bears to do that.

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-02-26 11:30 GMT+01:00 AbdealiJK <notifications@github.com>:

**Comment by sam09** [comment]
Hey. I see that this issue is assigned to no one. I would like to work on it, if that's cool

**Comment by AbdealiJK** [comment]
@sam09 Ive assigned this to you

**Comment by sam09** [comment]
@AbdealiJK This is what i thought of doing 
By adding all the jshint options to the signature of run function of JSHintBear we can access the options in the bear (Like Markdownbear). When .jshintrc is not specified, it will generate it automatically.

What do you think?

**Comment by AbdealiJK** [comment]
@sam09 That sounds like a good plan.

Btw - check out the `config_file` function in `Lint` which should help you out to make a temporary `.jshintrc` file. (I don't think jshint has cmd line options for all the options in jshintrc)

**Comment by sam09** [comment]
@AbdealiJK Thanks

**Comment by sam09** [comment]
@AbdealiJK I don't get the ``config_file`` function. It just returns ``None``.

**Comment by sam09** [comment]
I have implemented something like ``MarkdownBear`` where I have all the configs stored in an object. The part that remains is to create a temporary .``jshintrc`` file.

**Comment by sils1297** [comment]
http://coala.readthedocs.org/en/latest/API/coalib.bearlib.abstractions.html#coalib.bearlib.abstractions.Lint.Lint.config_file

**Comment by sam09** [comment]
@sils1297 @AbdealiJK I have tried ``config_file`` but i can't really get it working. Currently I have implemented it by creating a json file. However it is as persistent and not temporary.

**Comment by AbdealiJK** [comment]
@sam09 the `config_file` function is something you need to override in the Linter. It should get the sections and give out a list of lines you want in the file. the `generate_config_file` function then uses this to create a temporary file and send it to the `{config_file}` in `arguments`.

**Comment by sam09** [comment]
@AbdealiJK  I have tried using the ``{config_file}`` function but somehow it does not work. Instead I called the ``generate_config_file`` function and then gave the tempfile as argument and everything looks fine. I have been trying for a day now. Shall open a PR with what I have done?

**Comment by AbdealiJK** [comment]
Sure

-----Original Message-----

**Comment by jack17529** [comment]
Anything remaining  after this commit?
