### ISSUE TITLE
formatr

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala-bears#118]
http://yihui.name/formatR/

**Comment by AbdealiJK** [comment]
Out of curiosity why is important medium ? Does someone want to use this bear ?

**Comment by sils1297** [comment]
Yeah I know someone who wants so it's kind of a "customer request" if you can say this for OS projects. Secondly, R is used in research a lot and we want to bring coala to researchers as they're the ones who potentially do research on static code analysis.
