### ISSUE TITLE
Use http://httpstat.us/ in InvalidLinkBearTest

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala-bears#119]
http://httpstat.us/ is a super neat website to test all error codes.
Would be standardized to check them with it - http://httpstat.us/

**Comment by SanketDG** [comment]
@AbdealiJK Anything wrong with `http://httpbin.org`?

**Comment by AbdealiJK** [comment]
I didn't know we already did something similar. Closing this
