### ISSUE TITLE
Rename IndentBear to GNUIndentBear

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala-bears#120]

**Comment by sils1297** [comment]
we're working on some generic indentation so we should be clear on this

**Comment by SanketDG** [comment]
@coderx1 are you still working on this?

**Comment by coderx1** [comment]
Hi,

I am not yet comfortable with the process of git, I will try to brush up my
git knowledge so that I can put my time efficiently.
You can assign the task to others I will get back to you guys soon, I need
to work on git.

Thanks for cooperation
Sandeep

**Comment by SanketDG** [comment]
@coderx1 Sure, take your time. Just checking up on you. If you are stuck, in regards to this issue, come to gitter.

**Comment by coderx1** [comment]
Nah,
Except you the other people on Gitter are not helpful.,I will practice git
on my account by making some test repo, Also I am researching on some of
the GSoC projects cuz I want to bag one project this summer. So it will
take time, It will be better if you assign the bug to other person,
Thanks :)

**Comment by sils1297** [comment]
> Except you the other people on Gitter are not helpful

Hey, would you mind telling us if we're not helpful? We don't bite and we actually want to be helpful so if you're telling us that'd be helpful :)

**Comment by coderx1** [comment]
Lasse, Thanks for all your help and cooperation. :)

**Comment by MayankVachher** [comment]
@sils1297, I would like to assign this task to myself.

**Comment by sils1297** [comment]
@MayankVachher actually this one's kind of relevant, could you submit a PR within the next hour or so and then work with us to get it accepted today? If this doesn't work out with your plans I'd rather recommend you take another issue which is totally fine. (We want to do a release today and name changes are better in this release than in the next one as we want to get more stable over time.)

**Comment by MayankVachher** [comment]
@sils1297 Sure.
