### ISSUE TITLE
CMake bear

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala-bears#127]
Are there tools to lint CMake files?

My best friend told me it would be nice to have :3

**Comment by sils1297** [comment]
sure it would, did you query duckduckgo?

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-02-28 17:19 GMT+01:00 Mischa Krüger <notifications@github.com>:

**Comment by Makman2** [comment]
https://github.com/richq/cmake-lint
:D

**Comment by Makman2** [comment]
and
https://pypi.python.org/pypi/polysquare-cmake-linter/0.0.5

**Comment by AbdealiJK** [comment]
Assigned you @nishant-mor
