### ISSUE TITLE
Mock tests for InvalidLinkBear 

### ISSUE THREAD

**Issue by abhsag24** [coala-analyzer/coala-bears#133]
So right now the tests for InvalidLinkBear connects to the internet, instead of this  we should mock the requests, in order to make the tests faster and avoid failures in case of an unstable internet connection

**Comment by arafsheikh** [comment]
This would be nice, since `InvalidLinkBearTest` runs the slowest among all tests. One way to do this will be starting a HTTP server inside the test. If this is approved I would like to work on it.

**Comment by AbdealiJK** [comment]
I think a simpler version is just overwrite `requests.head()` temporarily during the test to give what ever sattus code and stuff we want ?

**Comment by arafsheikh** [comment]
Halfway fixing this I've realized that it's best for the tests to run online. Not all requests can/should be run locally, and for simplicity it won't be a good idea to have few test online and others offline.

**Comment by AbdealiJK** [comment]
@arafsheikh I think the better method is still to just override requests.head - you can do anything with it

We can alwats have a few tests with a real website too

**Comment by abhsag24** [comment]
I think its best to keep all tests offline, this one breaks ci too in a lot of cases, where the test times out some times resulting in a test failure, and it is a problem especially for newcomers, AFAIK keeping test offline would be more reliable since we would know exactly when the bear should yield a result and when it shouldn't  and not depend on a different server(which could be down sometimes), @arafsheikh  could you please explain which of the tests should be not be run locally?

**Comment by arafsheikh** [comment]
@AbdealiJK How can you override requests.head from within the test?

@abhsag24 We've got tests for `http://httpbin.org/status/***` and some real websites. The httpbin.com tests can be replicated offline but I thought it's best to leave the normal website tests intact.

**Comment by AbdealiJK** [comment]
just do:

```
def mock_requests_head(some_arg, etc etc):
    # whatever you want the request.head to return comes here
old_requests_head = requests.head
try:
    requests.head = mock_requests_head
    # Any code here will use the mocked requests.head
finally:
    requests.head = old_requests_head
```
This way your temporarily changing the value and later ti will be set back to the original value

**Comment by abhsag24** [comment]
@arafsheikh  i think there's no problem ethically speaking, in mocking these requests, they are just a bunch of valid and invalid links :D

**Comment by sils1297** [comment]
could we possibly start using a proper mocking library? We're mocking in
some places but not really clean...

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-03-05 11:24 GMT+01:00 Abhay Raizada <notifications@github.com>:

**Comment by arafsheikh** [comment]
@AbdealiJK How will the bear know if the current run is a normal run or a test? Can we pass custom arguments in `verify_local_bear`? 

@abhsag24 You are right. Those tests don't make sense.

**Comment by AbdealiJK** [comment]
@arafsheikh the mocking will NOT be done in the bear. It will be done in the Test.
You cannot use `verify_local_bear` in this case. You'll have to write a custom unittest.TestCase or use the LocalBearTestHelper directly.

**Comment by arafsheikh** [comment]
@AbdealiJK Whatever we do, at some point the `run()` method of the bear will be executed and will query the `status_code`. I don't understand how we'll stop the bear from using that status_code without making the bear aware of the test.

**Comment by abhsag24** [comment]
@arafsheikh as @sils1297 you could use the requests-mock library, it has some cool contextmanagers, which can help you give your own headers and whatnot and as long as you make requests from those contextmanagers everything should be fine :D

**Comment by sils1297** [comment]
requests-mock sounds good!

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-03-05 11:48 GMT+01:00 Abhay Raizada <notifications@github.com>:

**Comment by arafsheikh** [comment]
Something on similar lines?
http://pastebin.com/ETbnvdkB

**Comment by sils1297** [comment]
that'd work fine IMO

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-03-05 12:38 GMT+01:00 Sheikh Araf <notifications@github.com>:

**Comment by abhsag24** [comment]
@arafsheikh but that beats the point doesn't it? what @AbdealiJK was to stub the `requests.head` function since that is well a tested function in their library we don't need to test that,  while `get_status_code_or_error(url)` is a function that is written within the InvalidLinkBear class so overwriting that method means that method never gets tested?IMO you should go with as @AbdealiJK suggested or use the requests-mock library

**Comment by sils1297** [comment]
using the requests mocking would be cleaner because of that indeed

**Comment by AbdealiJK** [comment]
I was about to post the same thing that @abhsag24  posted.
I also think verify_local_bear can't be used. We're trying to overload it to do a complicated task - which was not why it was created.

**Comment by abhsag24** [comment]
@arafsheikh sorry but assigning this to myself, since its kind of important and we need a fix soon , maybe you can try taking up something else? :)
