### ISSUE TITLE
GitCommitBear: body_line_length shall be 72 and not 73

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala-bears#137]
The standard git commit guidelines suggest wrapping the body at 72 chars. So just replace the default of 73 with 72.

**Comment by AbdealiJK** [comment]
Needed in `coala` too

**Comment by Adrianzatreanu** [comment]
unassigned due to having already fixed a newcomer issue :)

**Comment by sims1253** [comment]
assign me

**Comment by Adrianzatreanu** [comment]
all yours.
