### ISSUE TITLE
One function for checking prerequisites

### ISSUE THREAD

**Issue by SanketDG** [coala-analyzer/coala-bears#146]
Currently there are two functions, one in `/home/sanket/coala-bears/bears/CheckPrerequisites.py` and another that exists as a `classmethod` in some bears. They should be merged into one function, that can be used for all bears.

**Comment by Makman2** [comment]
Do we really need `CheckPrerequisites`? I don't think we actually need to invoke the program^^

**Comment by Makman2** [comment]
@SanketDG and could you search for all bears manually redefining `check_prerequisites` and post them here?

**Comment by SanketDG** [comment]
Do I really need to do it manually? Pretty sure a simple grep could give what I want:

```
❯ grep -nr "def check_prerequisites(" 
bears/general/InvalidLinkBear.py:13:    def check_prerequisites(cls):
bears/natural_language/LanguageToolBear.py:16:    def check_prerequisites(cls):
bears/vcs/git/GitCommitBear.py:13:    def check_prerequisites(cls):
bears/r/RLintBear.py:22:    def check_prerequisites(cls):  # pragma: no cover
```

**Comment by Makman2** [comment]
No git grep suffices, just for having them inside this issue^^
