### ISSUE TITLE
XML validation via XSDs

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala-bears#155]
I don't know whether existing linter-bears already support this, but this would be a nice feature (like in https://github.com/coala-analyzer/coala-bears/issues/63).

I hope there's no issue for this already...

**Comment by sils1297** [comment]
We have an issue for validating XML against scheme

**Comment by AbdealiJK** [comment]
I'm marking this as a duplicate as we already have `XMLBear` using `xmllint`

**Comment by AbdealiJK** [comment]
The earlier issue is at https://github.com/coala-analyzer/coala-bears/issues/32

**Comment by sils1297** [comment]
@AbdealiJK this is not a duplicate, the existing bear checks for valid XML, this one shall validate if the given XML complies to a given schema!

**Comment by AbdealiJK** [comment]
From what I understand `xmllint` checks if the file is valid based on the schema mentioned in the DOCTYPE. Which is the most natural thing...

You can even specify an arg `dtdvalid` if you want to manually specify a schema. (Which is not there yet in the bear)
If that's what you wanted, then you can reopen it and modify title to add args to the XMLBear ?

**Comment by sils1297** [comment]
it's another issue, can you open a new one?

**Comment by Makman2** [comment]
So is this a duplicate now or not? I can't find the "old" issue that describes this bug^^

**Comment by sils1297** [comment]
well it kind of is because there's a way to do that with a bear we already have, thus #212
