### ISSUE TITLE
dart sdk - use the cache

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala-bears#157]
We cache the dart sdk folder, but we keep reinstalling it without checking if it's installed already in circleci.

**Comment by Adrianzatreanu** [comment]
i feel guilty

**Comment by Adrianzatreanu** [comment]
ill try working on this, even though i remember i tried doing all these and it failed miserably, but ill try again now :)

**Comment by Adrianzatreanu** [comment]
Hm how exactly are we to check if its already installed?
Check if it exists at that path already?

**Comment by AbdealiJK** [comment]
Just do `dartlint -v` ? or `dart -v` ? and see if the exitcode is 0 or not

**Comment by Adrianzatreanu** [comment]
well for some reason it would have a != 0 exit code even if the command existed, so i tried a different approach. what do you think?
