### ISSUE TITLE
Move apt-get command

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala-analyzer/coala-bears#170]
Right now, we have a `` $ sudo apt-get `` command that is in the Lua section in the .ci/deps.sh file.
This should be moved along with the other `` $ sudo apt-get `` commands in the same file.

**Comment by vivek425ster** [comment]
@Adrianzatreanu 
Where do we need to move it ?

**Comment by SanketDG** [comment]
@vivek425ster yes, right on!
