### ISSUE TITLE
Add jruby lint bear

### ISSUE THREAD

**Issue by Nosferatul** [coala-analyzer/coala-bears#175]
i think a bear for jruby would be cool to have!
https://github.com/jruby/jruby-lint

**Comment by Adrianzatreanu** [comment]
all yours then

**Comment by Nosferatul** [comment]
I didn't find any linter, also last update of https://github.com/jruby/jruby-lint was 3 years ago. I wanna be unassigned.

**Comment by sils1297** [comment]
see https://github.com/jruby/jruby-lint/issues/16

**Comment by tushar-rishav** [comment]
For reports on technical problems such as the use of undefined methods/variables,  [ruby-lint](https://github.com/YorickPeterse/ruby-lint) seems promising,
For reports on style check stuffs [rubocop](https://github.com/bbatsov/rubocop) looks good,
Finally there is this pacakge called [laser](https://github.com/michaeledgar/laser). It's quite old though. So  we might wanna go with the first two? @sils1297 @Nosferatul

**Comment by sils1297** [comment]
We should definitely take rubocop, that looks like it can do lots of cool stuff.

**Comment by sils1297** [comment]
ruby-lint too :) Awesome, maybe close this one and open issues for rubocop and ruby-lint?

**Comment by sils1297** [comment]
that is if we decide to not use jruby lint, we can have that too

**Comment by tushar-rishav** [comment]
Closing in favor of https://github.com/coala-analyzer/coala-bears/issues/189 and https://github.com/coala-analyzer/coala-bears/issues/190
