### ISSUE TITLE
requests_mock: Move to test-requirements

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala-bears#180]
requests_mock is used for testing InvalidLinkBear.

It's currently in requirements.txt
We should move it to test-requirements.txt

**Comment by mukeshmk** [comment]
I would like to be assigned to this.
I have already started working on this, I did make a few mistakes but I will correct it shortly.

Thank You.

**Comment by abhsag24** [comment]
@mukeshmk are you still solving this issue? if you need any help do reach us on [gitter](https://gitter.im/coala-analyzer/coala)

**Comment by sils1297** [comment]
unassigning due to inactivity, ping us if you're actually still working on it

**Comment by chriscoyfish** [comment]
I will work on this issue.
