### ISSUE TITLE
InvalidLinkBear: Distinguish bad connection from Broken Link 

### ISSUE THREAD

**Issue by abhsag24** [coala-analyzer/coala-bears#184]
so sometimes InvalidLinkBear yields results when we have a bad internet connection, but the links used were alright.

**Comment by AbdealiJK** [comment]
Give examples please

**Comment by sils1297** [comment]
uhm the InvalidLinkBear has a connection check in the prerequisites check
and should thus detect a broken connection, can you elaborate?

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-03-08 10:51 GMT+01:00 Abhay Raizada <notifications@github.com>:

**Comment by abhsag24** [comment]
so the InvalidLinkBear checks the connection only when its instantiated after that if a connection is lost or is unstable, it does have a problem in distinguishing the bad connection from a broken link

**Comment by AbdealiJK** [comment]
So we should have a max tries config in coafile and fail if it doesnt work
after max tries ?

**Comment by abhsag24** [comment]
@AbdealiJK but if the connection is permanently lost it would again yield a result though it shouldn't though it would improve our results on an unstable connection.

we could also  just  improve the message clarifying that it's either a `broken link or a bad connection`

**Comment by AbdealiJK** [comment]
I think if its a bad connection we shuld use `self.err()` and give a
warning rather than a result.
Giving a result message with "or bad connection" isnt a good idea imo

**Comment by AbdealiJK** [comment]
@SanketDG can you solve this quick-ish ?
This is a pretty important bug and I am marking it for milestone v0.1

**Comment by SanketDG** [comment]
Most of the connection problem went away with mocking the tests.

Closing as per as discussion with @abhsag24
