### ISSUE TITLE
Add ruby lint bear using rubocop.

### ISSUE THREAD

**Issue by Nosferatul** [coala-analyzer/coala-bears#189]
https://github.com/bbatsov/rubocop

**Comment by mr-karan** [comment]
Can I work on this ?

**Comment by tushar-rishav** [comment]
We already have similar issue opened at https://github.com/coala-analyzer/coala-bears/issues/175. Maybe we can work on rubocop and ruby-lint once we've come to a conclusion with the former one?
Shall we close the old issue? 
@sils1297

**Comment by sils1297** [comment]
@tushar-rishav IMO we should close #175 and open a new one for ruby-lint (not jruby-lint!)

**Comment by tushar-rishav** [comment]
@mr-karan As asked, you've been assigned.

**Comment by mr-karan** [comment]
Issue with the bear: 
'''
while true
  do_something
end

until false
  do_something
end
'''
![second](https://cloud.githubusercontent.com/assets/5689132/13630796/2400ab6a-e607-11e5-84f8-626d5eb37400.png)

'''
unless success?
  puts 'failure'
else
  puts 'success'
end
'''

![first](https://cloud.githubusercontent.com/assets/5689132/13630785/205b4056-e607-11e5-8a22-cf026ceaa1ca.png)

**Comment by sils1297** [comment]
@mr-karan can you make a PR and discuss it there? This issue is not related to the task but to your particular implementation and the discussion thus doesn't belong here, nobody is able to help you because you didn't share the code :/

**Comment by franzejr** [comment]
@sils1297, is it easy to add air bnb style guide? https://github.com/airbnb/ruby/issues/94

**Comment by sils1297** [comment]
Hey,

coala doesn't provide a "presets" mechanism yet (we should think about
that!), however if the rubocopbear has a setting for presets already
this'll be easy to do.

Greetings from London - maybe @Redridge can help you further.
