### ISSUE TITLE
JSLint Bear

### ISSUE THREAD

**Issue by arafsheikh** [coala-analyzer/coala-bears#196]
http://javascriptlint.com/index.htm

The linter can be downloaded via `npm`. (See: http://stackoverflow.com/a/8872851)

`difficulty/low`

**Comment by sils1297** [comment]
Is there an advantage over jshint and eslint?

**Comment by arafsheikh** [comment]
It follows a different standard than JSHint.

A) Passes JSHint out of the box - fails JSLint

```javascript
(function() {
  "use strict";
  var x=0, y=2;
  function add(val1, val2){
    return val1 + val2;
  }
  var z;
  for (var i=0; i<2; i++){
    z = add(y, x+i);
  }
})();
```

B) Passes Both JSHint and JSLint

```javascript
(function () {
    "use strict";
    var x = 0, y = 2, i, z;
    function add(val1, val2) {
       return val1 + val2;
    }
    for (i = 0; i < 2; i += 1) {
        z = add(y, x + i);
    }
}());
```

Reference: http://stackoverflow.com/a/10763615

**Comment by mr-karan** [comment]
JSHint is actually a fork of JSLint but I don't see any advantage to use this. In fact it is non configurable

**Comment by arafsheikh** [comment]
@mr-karan I guess you're right, it's not very configurable.
Also it hasn't been updated in two years.

@sils1297 Should I close this?

**Comment by Makman2** [comment]
@arafsheikh sure if you think the tool is not worth it :+1:
