### ISSUE TITLE
Move `bears.natural_language.MarkdownBear` to a new "markdown" folder

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala-bears#208]
Markdown is an own language specification, though you write texts in it, this doesn't really belong to natural language^^

**Comment by djkonro** [comment]
Please assign me to this task. I want to work on it.

**Comment by djkonro** [comment]
I would like to know if this change should make both within coala and coala-bears

**Comment by abhsag24** [comment]
@djkonro only within the bears, there should be no `MarkdownBear` inside of the coala repo, also you would need to change the import statement inside of tests
