### ISSUE TITLE
pypi time out

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala-bears#217]
http://www.rultor.com/t/7628-195392435

PyPi seems to time out frequently in rultor.
Maybe we can do something about it ? (happens frequently)

**Comment by sils1297** [comment]
ask on #distutils?

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-03-11 16:22 GMT+01:00 AbdealiJK <notifications@github.com>:

**Comment by AbdealiJK** [comment]
I attempted asking on # distutils - didn't get any response.

http://stackoverflow.com/questions/14219499/pypi-server-response-500 suggests specifying the pypi server name and index name ? Can try that ...

**Comment by AbdealiJK** [comment]
Bump
Does this still happen frequently ?
Note that I've seen that frequently pypi gives an error, but the package has actually been uploaded correctly.
In such cases, we cant even do a retry because the version numbers would clash

**Comment by sils1297** [comment]
indeed doesn't seem to happen anymore
