### ISSUE TITLE
Tests/ESLintBear: Unnecessary import

### ISSUE THREAD

**Issue by mr-karan** [coala-analyzer/coala-bears#225]
[`from coalib.misc.ContextManagers import prepare_file`](https://github.com/coala-analyzer/coala-bears/blob/master/tests/js/ESLintBearTest.py#L5) isn't used anywhere. Why is this imported then?

**Comment by sils1297** [comment]
cool can be removed then

**Comment by AbdealiJK** [comment]
Why is  PyUnusedCodeBear (or whatever it is named) not detecting these ?

**Comment by sils1297** [comment]
because it's a third party import I think and may have side effects?

**Comment by sils1297** [comment]
we may need to configure the `*_party` things
