### ISSUE TITLE
Julia bear integration

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala-bears#23]
_From @sudheesh001 on February 14, 2016 18:57_

Julia is a high-level, high-performance dynamic programming language for technical computing, with syntax that is familiar to users of other technical computing environments.

It looks like there's a linter available here https://github.com/tonyhffong/Lint.jl

_Copied from original issue: coala-analyzer/coala#1482_

**Comment by sils1297** [comment]
_From @AbdealiJK on February 16, 2016 11:42_

@niraj8 are you still working on this ?

**Comment by sils1297** [comment]
_From @niraj8 on February 16, 2016 13:23_

@AbdealiJK I have read the docs for writing a Bear and gone through other Bears in the repo, but I haven't written any code yet. I'll work on it today.

**Comment by SanketDG** [comment]
@niraj8 Ping. Please report whether you are still working on this?

**Comment by SanketDG** [comment]
Please assign this to me.
