### ISSUE TITLE
GitCommitBear: Check for imperative

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala-bears#243]
https://github.com/PyCQA/pydocstyle/blob/master/src/pydocstyle.py#L1613

pydocstyle does a really interesting simple check to check whether a docstring begins with an imperative word or not.

We should do this. It would probably help us a lot. (lots of newcomers make this mistake)
They basically check if the first word ends with `s` or not. (They ignore `ss`). Although this seems simple, pydocstyle is extensively used. So, empirically it works.

The problem we have is: How do we find the first word ? (Maybe we use the first word by default or ask a regex from the user to get the word which this test should be done on. In our case we would want it after `:` if the `:` exists ...)

```python
    def check_imperative_mood(self, function, docstring):  # def context
        """D401: First line should be in imperative mood: 'Do', not 'Does'.
        [Docstring] prescribes the function or method's effect as a command:
        ("Do this", "Return that"), not as a description; e.g. don't write
        "Returns the pathname ...".
        """
        if docstring:
            stripped = ast.literal_eval(docstring).strip()
            if stripped:
                first_word = stripped.split()[0]
                if first_word.endswith('s') and not first_word.endswith('ss'):
                    return D401(first_word[:-1], first_word)
```

**Comment by sils1297** [comment]
hm, this wouldn't catch `Removed something` which is way more usual than `Removes something`. People would also use `Removing something`.

**Comment by sils1297** [comment]
i.e. commit messages are quite something else than doc comments, where you don't write in past tense e.g.

**Comment by AbdealiJK** [comment]
True, but it's a start.
If we want a better / more complicated way - NLTK is the way

**Comment by sils1297** [comment]
hey that could be fairly easy with nltk, I guess it's childsplay for them

**Comment by sils1297** [comment]
http://stackoverflow.com/questions/30016904/determining-tense-of-a-sentence-python

**Comment by mr-karan** [comment]
This is a neat solution http://www.clips.ua.ac.be/pages/pattern-en#modality

**Comment by AbdealiJK** [comment]
That does look cool :+1:

**Comment by mr-karan** [comment]
Ah sadly no Python3 support  :-1:

**Comment by Makman2** [comment]
can we use 2to3 tool?

**Comment by sils1297** [comment]
So one would use nltk for that?

**Comment by tushar-rishav** [comment]
Since we are interested in first word after `:` we can just use `nltk.word_tokenize` to get list of words and finally get the word next to first occurrence of `:` in the list. Something like this maybe?

```python
words = nltk.word_tokenize(doc_string)
first_word_index = words.index(':') + 1
run_check(  words[first_word_index] ) # Run check for imperative mood
```

**Comment by sils1297** [comment]
I think we can just let nltk look at all words and if any non imperative mooded word is in there fail it?

**Comment by tushar-rishav** [comment]
Why not fix the commit and show the message? I am thinking of why not make this bear more flexible. At coala we check for imperative, but maybe at some other orgs they might have different requirements. Why not let user feed the `grammar/rule` and then we check if the grammar is applicable with commit msg. Of course we will have default grammar as imperative mood

**Comment by sils1297** [comment]
Imperative is like *the* standard, you mean automatically adapting the tense? coala can't fix the commit message :/

**Comment by tushar-rishav** [comment]
Is it? Wasn't aware of that. :+1: 
Hm yeah, that'd be tricky. Changing commit would require to open an editor and stuff with an automation. Cool. I guess it's pretty clear then. 
Can I work on this if we've come to the conclusion? :D

**Comment by sils1297** [comment]
Conclusion:

- no automatic change because coala doesn't support it
- just check the first line for imperative tense using nltk

**Comment by tushar-rishav** [comment]
Awesome. Assigning myself :+1:

**Comment by tushar-rishav** [comment]
@sils1297 @AbdealiJK  Hey. There has been some drawbacks in determining parts of speech using *nltk*. So when I was going through nltk docs (and writing some tests) I found that the way nltk handles parts of speech is bit not accurate. Um with some research I came across the fact that nltk was trained with Wall Street journals and similar other journals data. And they don't have a lot of imperatives. Consequently, nltk would call `add` as Noun in cases like `Add some stuff`. 
I came across with a maybe *acceptable* hack for this problem with slight modifications:

```python
import nltk


def parse(paragraph):
	"""
		Parse the given paragraph for Imperatives
		:param paragraph: The input paragraph
		:returns: 'Pass' or 'Fail' 
	"""
	f_sentence = nltk.sent_tokenize(paragraph)[0]	# Test the first sentence only
	words = nltk.word_tokenize(f_sentence)
	is_imperatives = []
	# VBZ : Verb, 3rd person singular present, like 'adds', 'writes' etc
	# VBD : Verb, Past tense , like 'added', 'wrote' etc
	# VBG : Verb, Present participle, like 'adding', 'writing'
	for word, tag in nltk.pos_tag(['I']+words)[1:]:
		if word.endswith('ing'):	# Handle special case for VBG
			is_imperatives.append((word, tag))
		elif tag.startswith('VBZ') or tag.startswith('VBD') or tag.startswith('VBG'):
			is_imperatives.append((word, tag))
	return "Pass" if not len(is_imperatives) else ("Fail", is_imperatives)

print(parse(raw_input()))

```
You can go ahead and test this snippet ( copy paste in terminal :P ).
 Let me know if It's acceptable in our case so that I can proceed further. :)

**Comment by tushar-rishav** [comment]
Another approach (which is fairly complex and probably also not generic) is using Regex in Chunking. So it works like we define patterns which is basically a sequence of part-of-speech tags. We then use the defined patterns to chunk the phrase and do processing. IMO this would be an overkill. I like the former approach. It's simple.

**Comment by Makman2** [comment]
In fact we could support a custom git-command action, *but*: I don't want coala to alter my commit message as this changes the commit history, imo everyone should decide on its own to change the message actually and how to alter the history^^

**Comment by tushar-rishav** [comment]
@Makman2 Yeah so It won't alter the commit message. It'd just report if commit message is acceptable or not. If not acceptable then just fail. I think that's what we wanted in first place?

**Comment by Makman2** [comment]
@tushar-rishav yeah, just wanted to state that I'm not a fan of interrupting my git workflow :D

**Comment by tushar-rishav** [comment]
@Makman2  Yeah.  :+1:  :D
