### ISSUE TITLE
XMLBear: Results are shown as log messages

### ISSUE THREAD

**Issue by vivek425ster** [coala-analyzer/coala-bears#251]
https://asciinema.org/a/6nt1tuju6hv0b1l5ga8zsdgv7

**Comment by sils1297** [comment]
is this a bugfix? Do we want a backport?

**Comment by vivek425ster** [comment]
@sils1297 It is a bug fix

**Comment by sils1297** [comment]
reopening for backporting

**Comment by sils1297** [comment]
backport happened
