### ISSUE TITLE
docs don't build - really

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala-bears#259]
```
Warning, treated as error:
/home/lasse/prog/coala-bears/bears/js/JSHintBear.py:docstring of bears.js.JSHintBear.JSHintBear.run:188: ERROR: Unexpected indentation.
```

**Comment by sils1297** [comment]
not ok!

**Comment by AbdealiJK** [comment]
Were we not testing this in circleci ?

**Comment by sils1297** [comment]
we should but locally it didn't build, I released anyway as docs are online

**Comment by vivek425ster** [comment]
https://circleci.com/gh/coala-analyzer/coala-bears/781
It is showing that in the circleci as well.
But why circle ci is not failing ?

**Comment by AbdealiJK** [comment]
It seems `python setup.py docs` isnt giving out an exitcode of the commands
it runs.

**Comment by sils1297** [comment]
that should be quickly fixed, can somebody take it? Add the exitcode and correct the docs in two different commits.

**Comment by vivek425ster** [comment]
@sils1297 Please assign this to me.
