### ISSUE TITLE
PyImportSortBear add more args

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala-bears#26]
_From @AbdealiJK on February 10, 2016 20:42_

https://github.com/timothycrosley/isort/wiki/isort-Settings

known first and third party imports needs to be added to PyImportSortBear

_Copied from original issue: coala-analyzer/coala#1403_

**Comment by ravinimmi** [comment]
@sils1297 Please assign me.

**Comment by sils1297** [comment]
@ravinimmi you're way beyond newcomer status, we'd like to ask you to leave this and other newcomer issues to actual newcomers because we struggle to come up with enough newcomer issues.

**Comment by AbdealiJK** [comment]
Hi @ravinimmi I notice you've already solved a few issues. Could you do some difficulty/low issues now ?
We normally prefer it when people only do 1-2 newcomer issues

**Comment by ravinimmi** [comment]
@sils1297 @AbdealiJK  Ok, got it.

**Comment by abpnd12** [comment]
please assign this to me

**Comment by AbdealiJK** [comment]
Ive invited you to the org. We can assign you once youve joined

**Comment by sils1297** [comment]
@AbdealiJK who?

**Comment by AbdealiJK** [comment]
@abpnd12 had commented on this saying he wanted to do it (I still have the mail) ... I think he deleted the comment ?

**Comment by abpnd12** [comment]
@AbdealiJK thank you for adding me, I'm still having issues while playing with the code so I deleted the comment . I'm sorry if it created any issue.

**Comment by AbdealiJK** [comment]
@abpnd12 Well, it's better not to delete stuff - rather comment again (otherwise it gets confusing)

And, do you still want to be assigned to this issue ?

**Comment by abpnd12** [comment]
not now, I'm having problems while understanding the code

**Comment by AbdealiJK** [comment]
Removing newcomer as it's blocking https://github.com/coala-analyzer/coala/issues/1529
