### ISSUE TITLE
GitCommitBear should  display by how much the shortlog is long 

### ISSUE THREAD

**Issue by abhsag24** [coala-analyzer/coala-bears#267]
so right now GitCommitBear just displays that the shortlog of HEAD commit is too long, though it'd be cool if it would display `Shortlog of HEAD commit is longer than limit by x characters`

**Comment by Makman2** [comment]
I usually use an editor that displays me the margin there. But yeah this is definitely useful.

**Comment by SanketDG** [comment]
Better:

If my shortlog is 90 chars and the `shortlog_length` is 79 chars,

```
Shortlog of HEAD commit is longer than limit by 11 characters (90 > 79)
```

**Comment by jarifibrahim** [comment]
Can someone assign this to me?
