### ISSUE TITLE
ESLint Bear

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala-bears#27]
_From @sils1297 on February 10, 2016 17:2_

http://eslint.org/docs/user-guide/formatters/#json

The json output even contains fixes - let's take this it's awesome.

_Copied from original issue: coala-analyzer/coala#1399_

**Comment by sils1297** [comment]
@sudheesh001 please use the json output as documented at http://eslint.org/docs/user-guide/formatters/#json , sample output properly formatted at http://pastebin.com/arTMxXq6 .

It'll give a neat output with instructions on how you can fix the problem so you can create a diff automatically and fix it for the user.

**Comment by sils1297** [comment]
You'll want to set the result origin to `ESLintBear (<rule>)` I think

**Comment by Adrianzatreanu** [comment]
@sudheesh001 Hey. Seems you have submitted no PR in the past 12 days, and this https://github.com/coala-analyzer/coala/pull/1438 had no update on the past 15 days :) Are you still working on this, do you need some help?

**Comment by AbdealiJK** [comment]
@Adrianzatreanu He had mentioned that he's going to continue this after some exams. He mentioned this 2 days ago on gitter

**Comment by Adrianzatreanu** [comment]
ok then :)
