### ISSUE TITLE
Add circleci, codecov and rultor

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala-bears#3]
Add circleci, rultor and codecov

 - Circleci needs to be enabled on their website
 - Codecov needs to be enabled (maybe also ass a secret token on circleci?)
 - Add pypi pushing in rultor - Needs that secret key thing to be done

**Comment by AbdealiJK** [comment]
@sils1297 could you do this by tomorrow ?

**Comment by sils1297** [comment]
circleci is enabled, codecov should work when you add the command as usual, if it doesn't ping me. I'll do PyPI until tomorrow 2 PM UTC.

**Comment by sils1297** [comment]
- [x] circle
- [x] codecov
- [ ] rultor

**Comment by sils1297** [comment]
basic rultor stuff is there, rest can be implemented in #7
