### ISSUE TITLE
InferBear

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala-bears#30]
_From @sils1297 on February 9, 2016 23:23_

http://fbinfer.com/ - works on Objective-C, Java, or C code and seems to do quite some cool stuff. I'm not sure where we want to put it as it doesn't really belong in one of the language folders, maybe in the c_languages...

This is a simple wrapper if infer is done properly it should be simple to do.

_Copied from original issue: coala-analyzer/coala#1364_

**Comment by sils1297** [comment]
_From @NalinG on February 10, 2016 7:26_

Hi, so we need to make a bear using infer to do stuff that infer does.
Please correct me if I am wrong

**Comment by sils1297** [comment]
_From @AbdealiJK on February 10, 2016 7:27_

Nalin, thats exactly what needs to be done

**Comment by sils1297** [comment]
_From @NalinG on February 10, 2016 7:34_

I would like to work on this bug, can you assign it to me.

**Comment by sils1297** [comment]
_From @NalinG on February 10, 2016 12:23_

Is it better to discuss here or on the gitter channel ?

**Comment by SanketDG** [comment]
@NalinG still working on this? We want to make sure you are still interested.

**Comment by sils1297** [comment]
@NalinG removing assignment as you seem to be unreachable (we pinged you on another bug as well)

**Comment by aachiritoaei** [comment]
Can I be assigned? I would like to work on it.
