### ISSUE TITLE
Add xo bear

### ISSUE THREAD

**Issue by mr-karan** [coala-analyzer/coala-bears#301]
> JavaScript happiness style linter :heart:

[XO](https://github.com/sindresorhus/xo)

Would be cool to have this?

**Comment by AbdealiJK** [comment]
I'm wondering if we should add so many js linter bears ?
If they provide no added advantage to eslint or jshintrc, isn't it better not to add it ?

**Comment by AbdealiJK** [comment]
In fact XO documentation says

> Uses ESLint underneath, so issues regarding rules should be opened over there.

**Comment by mr-karan** [comment]
Yep I did read that, but I was thinking from *more the merrier* point of view. I can close this if you want. 
And yes, we should work on making ESLint bear better (by providing an easy way of adding more plugins)

**Comment by AbdealiJK** [comment]
I agree with *more the merrier* but if this is just ESLint with a different set of default configs, then I don't see much point in it.
What exactly does XO bring to the linters ? Why was it even created ?

From the readme:
> Enforce strict code style. Never discuss code style on a pull request again!
> No decision-making. No .eslintrc, .jshintrc, .jscsrc to manage. It just works!

So, it seems like just a set of default configs for eslint.

@sils1297 could you take a call ?
I'm wondering if we should have a method to have different "sets" of default configs for a bear's args now. Something like "google style", "pep style", or similar ?

**Comment by sils1297** [comment]
I have no idea, sounds to me like eslint does the job and we should rather give it sane defaults and do the settings guessing properly.

**Comment by AbdealiJK** [comment]
Closing then as XO adds no new analysis functionality to coala.
