### ISSUE TITLE
Remove clang installation

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala-analyzer/coala-bears#303]
right now a ton of stuff fails tests due to clang, we might temporarily remove it to see if it is the problem?

**Comment by Makman2** [comment]
LLVM x64 was installed on the appveyor servers, and this is the cause of the problem. Hotfix already on its way on https://github.com/coala-analyzer/coala-bears/pull/304.
Closing in favor of https://github.com/coala-analyzer/coala-bears/issues/305 then.
