### ISSUE TITLE
LineCountBear: Make it useful

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala-bears#334]
Let's give LineCountBear a purpose and warn if a file is too big!

I have a commit ready but somebody needs to change tests for it to work.

difficulty/low

**Comment by Makman2** [comment]
yeah that's actually a usecase! :D

**Comment by sils1297** [comment]
it is! Don't make the fault and activate it in the coafile as gitmate doesn't have the setting yet and will yield lots of results :P I did that :/
