### ISSUE TITLE
Support easy_install

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala-bears#341]
Apparently travis container build does not support pip3. It suggests to use easy_install instead.

coala-bear's deps don't work with easy_install. But coala does.
Do we want it to be compatible ?

Error from travis build using easy_install: https://travis-ci.org/coala-analyzer/coala-html/builds/125156449

Errors when doing it locally:
```
$ easy_install coala-bears
Searching for coala-bears
Reading https://pypi.python.org/simple/coala-bears/
Best match: coala-bears 0.2.0.dev20160419161846
Downloading https://pypi.python.org/packages/03/31/0b879e5bb5b2e21bc8e674257b41759ba1df77972841ab159fcd2840e526/coala-bears-0.2.0.dev20160419161846.tar.gz#md5=6a878b1fa6e69b8e7f3ce8cfe7718633
Processing coala-bears-0.2.0.dev20160419161846.tar.gz
Writing /tmp/easy_install-0u5quzyn/coala-bears-0.2.0.dev20160419161846/setup.cfg
Running coala-bears-0.2.0.dev20160419161846/setup.py -q bdist_egg --dist-dir /tmp/easy_install-0u5quzyn/coala-bears-0.2.0.dev20160419161846/egg-dist-tmp-t14_gph2
Downloading bears/scala/scalastyle.jar...
error: [Errno 2] No such file or directory: 'bears/scala/scalastyle.jar'
```

**Comment by sils1297** [comment]
@AbdealiJK is that complicated?

**Comment by AbdealiJK** [comment]
I have no clue :)
The issue is with the scalastyle stuff, so I think easy_install cannot
install things from wget (in setup.py) for some reason. No idea why,
haven't checked it out.

I actually came across a work around where we can simply do:
```
sudo easy_install3 pip
sudo pip3 install coala-bears
```
So, we could actually close this I think and recommend that ...

**Comment by AbdealiJK** [comment]
Closing as accepting patches: not important, easy to install pip and then coala. So basically pip is a dependency of coala - which is alright.

**Comment by sils1297** [comment]
forgot to close huh?
