### ISSUE TITLE
annotation bear

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala-bears#37]
_From @sils1297 on November 13, 2015 13:28_

a bear that takes the language definition and annotates each line with simple properties like "from here to there is a comment", "from here to there is a string" and so on. This is intended to be used by other bears for simpler analysis functionality

_Copied from original issue: coala-analyzer/coala#1040_

**Comment by sils1297** [comment]
_From @AbdealiJK on December 12, 2015 5:45_

I think we may want a abstracted AST bear ?
Something that just creates ASTs (using pre existing packages) and let's each bear do things with them.

**Comment by sils1297** [comment]
The idea with this one was more simple, a real universal AST isn't really viable so the idea was that we have some light annotations here and provide some graphs and other language independent representation at other places so some algorithms might use different abstractions. Or we could try making an extensible AST later.

**Comment by srisankethu** [comment]
@sils1297 Can you assign me to this if you are not working on it

**Comment by AbdealiJK** [comment]
@srisankethu this is a pretty complicated issue (and I have a feeling itll depend on coalang again)
I know that he isnt working on this atm, so Im assigning you

Please share your method of how you plan to do ti before attempting to code it though - as I think this may be a bit complicated

**Comment by srisankethu** [comment]
@AbdealiJK Thank you

**Comment by srisankethu** [comment]
How do I approach this issue(some idea)

**Comment by AbdealiJK** [comment]
I'm not sure myself.
@sils1297 @Makman2 could you help out ?

**Comment by sils1297** [comment]
@srisankethu I'd recommend you rather try to take on a difficulty/low bug like writing a simple bear or so, IIRC you're rather new to coala. One difficulty of this issue is that we can't give you an idea on how to approach it because we don't know. That's part of the task.

**Comment by sils1297** [comment]
@abhsag24 might want to take this on since he's working on something related which actually might go well together with this idea

**Comment by srisankethu** [comment]
@sils1297 Okk

**Comment by sils1297** [comment]
Ok, we probably want:

1. A bear that creates sourceranges to determine which regions are comments
2. A bear that creates sourceranges to determine which regions are strings, depends on the comment marking
3. Other bears dependent on those that search for other useful stuff

So in the end if somebody only needs to know which are comments he just depends on 1 and we don't need to run the whole chain.
