### ISSUE TITLE
RuboCop: Add configs

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala-bears#372]
Part of https://github.com/coala-analyzer/coala-bears/issues/340

Assigning @abhsag24 as he said he was interested on gitter.

**Comment by AbdealiJK** [comment]
@abhsag24  A polite reminder about this, still working on it ?

**Comment by abhsag24** [comment]
@AbdealiJK  yes:) home now so expect a PR very soon :P

**Comment by sils1297** [comment]
Ping.
