### ISSUE TITLE
GNUIndent: Add more configs

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala-bears#373]
Part of https://github.com/coala-analyzer/coala-bears/issues/340

Assigning @rubdos as discussed on gitter.

**Comment by rubdos** [comment]
How wait, I thought you meant "GNU style indentation", not "GNUIndent". Never heard of that one, although for me it's okay if you want me to do it :P

**Comment by AbdealiJK** [comment]
You could make a new issue for the style indentation (making a bear for it) but this one is required too

-----Original Message-----

**Comment by AbdealiJK** [comment]
@rubdos A polite reminder about this, still working on it ?

**Comment by rubdos** [comment]
@AbdealiJK Have not worked on this yet. If it is more urgent then my schedule permits me, I am afraid you would better assign it to someone else... As I said earlier:

> [...] I thought you meant "GNU style indentation", not "GNUIndent". Never heard of that one, although for me it's okay if you want me to do it :p

It's  just not that I can set this as a priority at the moment :)

**Comment by Makman2** [comment]
Feel free to take it up when you like, until then I unassign it from you :)

**Comment by sils1297** [comment]
@Redridge interested to help out here?

**Comment by Asnelchristian** [comment]
Good morning, 
Can i be assigned to this ?
