### ISSUE TITLE
FormatRBear: Add configs

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala-bears#376]
Need to implement configs in the `tidy_source` function of this R package.

This seems really easy actually ! Just get configs and put it into the "arguments" of the Linter.

**Comment by sils1297** [comment]
@AbdealiJK time to do this yourself?

**Comment by Asnelchristian** [comment]
i would like to work on this

**Comment by SanketDG** [comment]
@Asnelchristian make us proud :smile:
