### ISSUE TITLE
Mention all languages in README

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala-bears#378]
Someone had suggested this before, but we had decided not to do it because it would make the readme too long.

We should make a table and mention all the Languages that we support so that the readme does not get too long. It looks good because it shows we have a LOT to offer and it is vital info in the README.

Example : https://github.com/guinslym/pyexifinfo#supported-filetype-read-only looks so much nicer whereas I need to dig up the docs (or code!) to find the supported file formats of other libraries

**Comment by sils1297** [comment]
@Adrianzatreanu progress?

**Comment by Adrianzatreanu** [comment]
not yet, mentioned when i took it that im doing it if its not urgent, been a long week, can surely give it a try today :) starting right away!

**Comment by Adrianzatreanu** [comment]
https://github.com/coala-analyzer/coala-bears/wiki/all-languages-prototype is the progress, waiting for feedback.
