### ISSUE TITLE
Clone Decection: Make variable/constatn/function a property of the CVs

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala-bears#38]
_From @sils1297 on July 24, 2015 14:10_

_Copied from original issue: coala-analyzer/coala#867_

**Comment by Uran198** [comment]
Is it about wrapping methods from [here](https://github.com/coala-analyzer/coala-bears/blob/master/bears/c_languages/codeclone_detection/CloneDetectionRoutines.py) into class?

**Comment by sils1297** [comment]
Yes, making the design around there a bit more OO.

**Comment by Uran198** [comment]
Ok, I'll work on this one.

**Comment by sils1297** [comment]
@Uran198 sorry I looked too briefly through this, actually the idea here was to take the existing CountVector class (CV = CountVector) and introduce a property that tells the user wether a CountVector is for a constant, function or a variable.

**Comment by sils1297** [comment]
Just putting methods into a class as static methods is usually not very useful...

If you still want to take this, take a look at the `ClangCountVectorCreator`, there I did some name mangling to determine what's a constant and what not (`self.count_identifier("#" + tokens[0].spelling)`), this is about making this an actual property.

If you don't want to do this task anymore I can totally understand that, also I think the judgement of difficulty/low is wrong.

**Comment by Uran198** [comment]
@sils1297 I found where you're doing mangling, but I couldn't found where you use it. Maybe it's not needed at all?

**Comment by sils1297** [comment]
@Uran198 it's used in `CloneDetectionRoutines.exclude_function` at least.

**Comment by sils1297** [comment]
Other than that I don't think it's used yet.
