### ISSUE TITLE
ClangCodeCloneDetectionBear: Add switch/case support

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala-bears#39]
_From @sils1297 on June 11, 2015 18:40_

Counting conditions for clang currently ignore that which is bad.

_Copied from original issue: coala-analyzer/coala#652_

**Comment by sils1297** [comment]
So the way to do this would be to count the condition with the `Is condition` CC and the bodies with the `In condition` CCs so nested things are recognized right.

**Comment by yland** [comment]
I would like to work on this task.

**Comment by sils1297** [comment]
Cool!
