### ISSUE TITLE
Check versions in package.json

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala-bears#412]
We use ~2.3.0 for eslint , maybe we should use ~2.3
`~2.3.0 => 2.3.0 or 2.3.x (x>0) ..... ~2.3 => 2.3 or 2.x (x>3)`

From pep440:
```
~= 2.2
>= 2.2, == 2.*

~= 1.4.5
>= 1.4.5, == 1.4.*
```

First, we need to check if the same is true for nodejs ...

**Comment by sils1297** [comment]
nope: https://docs.npmjs.com/misc/semver#tilde-ranges-123-12-1

**Comment by AbdealiJK** [comment]
Oh, I see. That's really confusing >_<

Then your commit is indeed correct
