### ISSUE TITLE
Upgrade coala

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala-bears#427]
Apparently when we upgrade coala, CI fails for Python 3.3.

See https://github.com/coala-analyzer/coala-bears/pull/423

**Comment by AbdealiJK** [comment]
I backtraced the issue, and found the reason to be that `CheckStyleBears` is the only linter which needs `create_arguments` to have `self`. When executing the bear, the bear is asking the Section for a non-optional config named `self`. This is causing the error to be thrown.

I am not sure what changes have been added in the new coala version ... So, I'm not sure why it didnt happen before. We should ignore the `self` param too.

**Comment by AbdealiJK** [comment]
Oh right. This only happens in py3.3
I wonder why ? This should actually fail for all of them.
@Makman2 ?

**Comment by Makman2** [comment]
hmm @AbdealiJK that was your change :D
The only problem is you need the logging. As the bear currently is broken, we should remove the log and add an issue / fixme to readd it again. Then we can change `known_configs` to a class/staticmethod and we are good to go :+1:

**Comment by Makman2** [comment]
Logging is generally a problem in coala and in my new linter design, need to do look at it too soon ...

**Comment by sils1297** [comment]
This was fixed with a fix at coala :)
