### ISSUE TITLE
Use Env:Plugin instead of Console

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala-bears#449]
Use `Environment :: Plugins` classifier in setup.py instead of `Environment :: Console`.

**Comment by sils1297** [comment]
why?

**Comment by AbdealiJK** [comment]
Because it's a plugin for coala

**Comment by sils1297** [comment]
oh right

**Comment by Asnelchristian** [comment]
i would like to work on this

**Comment by sils1297** [comment]
arent you assigned to two other issues so far?

**Comment by ujas800** [comment]
i want to work on this issue.........

**Comment by sils1297** [comment]
Hey @ujas800 I've assigned you! Feel free to ask us if you have any issues, I don't recall anyone ever doing his first issue without any help, especially later when it comes to rebasing and stuff. Thanks for your help!

**Comment by ujas800** [comment]
thanks @sils1297....!
