### ISSUE TITLE
Naming scheme for test classes using verify_local_bear

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala-bears#45]
_From @AbdealiJK on February 17, 2016 19:58_

The naming of classes and functions in tests should be normalized. 
Specially those using `verify_local_bear` where the names are as bad as `ProseLintBear1Test`, `ProseLintBear2Test`, etc

_Copied from original issue: coala-analyzer/coala#1560_

**Comment by AbdealiJK** [comment]
Was fixed in https://github.com/coala-analyzer/coala-bears/commit/f8ba231d49c41269deb8a5f09ca2a894b05f010a
