### ISSUE TITLE
Add support for RAML Lint

### ISSUE THREAD

**Issue by rhnvrm** [coala-analyzer/coala-bears#452]
RAML lint would be a cool feature to add. 

https://github.com/QuickenLoans/ramllint

[ @mr-karan @arafsheikh ]

**Comment by sils1297** [comment]
Hey @rhnvrm thanks for the report. We'll look into it. Are you interested in either using or developing this?

**Comment by rhnvrm** [comment]
I'm interested in using this. Thanks!

Sincerely,
Rohan Verma
hello@rohanverma.net
+91 9911296253

**Comment by sils1297** [comment]
Cool, then I'm scheduling this for the next release :)

**Comment by Adrianzatreanu** [comment]
If you need this, then I'm in!

**Comment by rhnvrm** [comment]
@sils1297 @Adrianzatreanu: Thanks! RAML is used by lots of API developers as well.

**Comment by sils1297** [comment]
@rhnvrm it has landed! You can try it out by running `pip install coala-bears --pre`

**Comment by Adrianzatreanu** [comment]
@rhnvrm RAML support has been successfully added to coala :)

**Comment by rhnvrm** [comment]
@sils1297 @Adrianzatreanu Thanks a lot for this! It was much needed! :+1:
