### ISSUE TITLE
checkstyle.jar: Download it as requirement-install-step

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala-bears#47]
_From @Makman2 on February 13, 2016 22:33_

I would propose for a clean requirement-install-handling to populate `./setup.py` with two new commands, e.g. `install-test-requirements` and `install-requirements`. These two commands shall do the pip install via `pip3 install -r requirements.txt` (or `test-requirements.txt`) and also allows to handle custom install steps like the checkstyle.jar download.

This also needs adaption inside the docs and CI-scripts!

_Copied from original issue: coala-analyzer/coala#1465_

**Comment by sils1297** [comment]
_From @AbdealiJK on February 14, 2016 4:40_

I think the better way to do it would be to add a install-requirements form each bear and let each bear handle it individually

Something like `check_prerequisites` we add a `install_prerequisites`.
Here the bear can do whatever it wants.
We can also add helper functions to run `pip`, `npm`, `gem` commands to make it easier.

This would also help in https://github.com/coala-analyzer/coala/issues/1304

We could even automate searching for `package.<bearname>.json` `requirements.<bearname>.txt` and `Gemfiles.<bearname>` inside the bear directory :)

**Comment by sils1297** [comment]
_From @Makman2 on February 14, 2016 22:15_

Not a bad idea^^

**Comment by SanketDG** [comment]
I am interested in doing this.

The first thing to do would be to add the two commands `install-test-requirements` and `install-requirements`. This is relatively easy, but what I don't understand is how the checkstyle.jar download comes in these two commads, do you mean by `install-requirements`, all possible requirements, even requirements from specific bears like `checkstyle.jar` and `scalastyle.jar`?

> I think the better way to do it would be to add a install-requirements form each bear and let each bear handle it individually
> 
> Something like check_prerequisites we add a install_prerequisites.
> Here the bear can do whatever it wants.
> We can also add helper functions to run pip, npm, gem commands to make it easier.

This is a great idea, and will work much better when we decentralize the bears. So every bear will have a `classmethod` named `install_prerequisites`, which will only process if `check_prerequisites` return a `str`.

To maintain the uniformity across bears, the above said things should be added to the Writing Bears tutorial.

As for linter bears, I will update my thoughts on a separate comment.

The helper functions should be in a separate file, `HelperFunctions.py` preferably in `bears/`

> We could even automate searching for package.<bearname>.json requirements.<bearname>.txt and Gemfiles.<bearname> inside the bear directory :)

I know about `pip` having a `-r` flag, but does `npm` and `gem` have something similar?

**Comment by AbdealiJK** [comment]
For `npm` if you have a `package.json` in the directory, it automatically uses that when you do `npm install`
For `gem` you normally use `bundler` and a `Gemfile` with it

**Comment by SanketDG** [comment]
@AbdealiJK I knew of those. What I was saying, was if npm and bundler can take in `package.<bearname>.json` and `Gemfiles.<bearname>` like you propose.

**Comment by AbdealiJK** [comment]
Apparently not
http://stackoverflow.com/questions/25991082/use-different-filename-for-npm-than-package-json

We *could* just make a temp dir, move it there and install stuff and then
move everything back ?
In bundler you can set an env variable it seems
http://stackoverflow.com/questions/4976132/can-i-rename-my-gemfile-to-gemfile-rb

**Comment by Adrianzatreanu** [comment]
ping @SanketDG :p i know youre there, pinging in case you forgot about the issue :D

**Comment by SanketDG** [comment]
Yeah this is kind of big. It will require some time and planning :smile: \
I'll pick this up after GSoC.

If anybody else is interested, its up for grabs.

**Comment by Makman2** [comment]
feel free to retake then :)
