### ISSUE TITLE
NLTK version increase

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala-bears#509]
NLTK has now become 3.2.1 which resolves the windows issue.
So, we can remove the constraint of "3.1 or lesser". They have also removed 3.2 from pypi so nobody can download it anymore.
http://stackoverflow.com/questions/35836907/nltk-v3-2-unable-to-nltk-pos-tag

**Comment by sils1297** [comment]
Task: increase nltk version to the latest in requirements.txt

**Comment by underyx** [comment]
Looks like this should be assigned to @harshdattani but is not.

**Comment by underyx** [comment]
Okay, that's fine, I can do it then :D
