### ISSUE TITLE
CoffeeLintBear: Use --stdin

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala-bears#517]

**Comment by Makman2** [comment]
any advantage using that?

**Comment by sils1297** [comment]
Sure, keep stuff in memory, less IO, coala may be used in editors with
files that aren't on the FS, @mr-karan might need it for inlined code.

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
http://coala-analyzer.org/ - http://viperdev.io/ - http://gitmate.com/

**Comment by Asnelchristian** [comment]
can i work on this ?
