### ISSUE TITLE
set up requires.io correctly

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala-bears#53]
_From @sils1297 on February 11, 2016 17:24_

doesn't seem to work

_Copied from original issue: coala-analyzer/coala#1421_

**Comment by sils1297** [comment]
it sends PRs now but they suck. Needs some further config anyway, maybe I'll just let it send me mails.

**Comment by sils1297** [comment]
This needs complete new setup for this repository.

**Comment by AbdealiJK** [comment]
@sils1297 what are the issues you faced btw ?
Do we still want it ?

**Comment by sils1297** [comment]
the commit messages of requires.io suck, that's all. Plus a few usability
things which made me pressing wrong buttons.

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-03-16 11:11 GMT+01:00 AbdealiJK <notifications@github.com>:

**Comment by Makman2** [comment]
If you don't like the commit message we just cherry-pick it out of the PR and change it accordingly, closng the PR from requires.io then^^

**Comment by sils1297** [comment]
then we can also just let us send an email :( I'd love if it could file an
issue

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-03-16 17:35 GMT+01:00 Mischa Krüger <notifications@github.com>:

**Comment by Makman2** [comment]
why not? :D

**Comment by sils1297** [comment]
not so sure anymore if we still want this...

**Comment by Makman2** [comment]
I think we do that quite well manually^^
