### ISSUE TITLE
Add CAN_FIX and CAN_DETECT to each bear

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala-analyzer/coala-bears#534]
These attributes currently exist, but we also need to use them. Each bear should hold information about what it can fix and what it can detect.

Both are sets, and can_detect takes everything from can_fix automatically (if one bear can fix something, it surely can detect it too)

**Comment by sils1297** [comment]
Yes we do need that ideally somewhen like today or tomorrow, whoever does that will get invited to an extra free meal by me personally at EuroPython. Any volunteers?

**Comment by Adrianzatreanu** [comment]
Why do you need it so fast?

**Comment by sils1297** [comment]
I want the info in for the release so we can update bear-docs. Also we need it for gitmate to evaluate now coala compares to other solutions and what analysis we offer which ultimately helps coala as well. So this is a super important thing that affects users directly and can help us develop the right bears in the futuer.

**Comment by Adrianzatreanu** [comment]
Do we have this somewhere I could take it from already? Or need to do it from scratch?

**Comment by sils1297** [comment]
We gotta do this from scratch, we only have a rough listing of what we can do but not per bear. Which means for every bear look up what it can do and put it there :/

**Comment by Adrianzatreanu** [comment]
I can help with this, but this surely takes a while because not all those options (syntax, etc) are posted somewhere, please post the link here for support though :p
not promising i do all 65 bears today or tomorrow though..

**Comment by Adrianzatreanu** [comment]
aaand done. forgot to include it because i split it into many commits and none was fit enough to bear the name of closing this issue :)

(see the pun? *bear*)
