### ISSUE TITLE
hlint for haskell

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala-bears#54]
_From @sils1297 on February 18, 2016 0:49_

this one suggests fixes sometimes with hints, awesome!

_Copied from original issue: coala-analyzer/coala#1565_

**Comment by sils1297** [comment]
https://hackage.haskell.org/package/hlint#readme

**Comment by Redridge** [comment]
solved here https://github.com/coala-analyzer/coala/issues/1565
