### ISSUE TITLE
change `tab_width` -- > `indentation_width`

### ISSUE THREAD

**Issue by abhsag24** [coala-analyzer/coala-bears#563]
currently `tab_width` in most bears is used as number of spaces to indent, it has nothing to do with tabs and should be changed to `indentation_width` like rubocop

**Comment by Makman2** [comment]
This task also involves changing documentation

**Comment by sils1297** [comment]
hey @Asnelchristian this mainly happened in the bears, I think @Adrianzatreanu needs to finish the docs move and then you should update the docs right?

**Comment by Nosferatul** [comment]
I wanna work on it. Wherever I find `indent_size='tab_width'` it should be changed in `indent_size='indentation_width'` ?

**Comment by Adrianzatreanu** [comment]
The documentation rework is complete for what its worth.

**Comment by Adrianzatreanu** [comment]
@Nosferatul yes, its a setting that some bears have.

**Comment by Adrianzatreanu** [comment]
hey @Asnelchristian from what i can see, you already changed to most bears from tab_width to indent_size. is this issue still needed?

**Comment by Asnelchristian** [comment]
oh yeah this is no more needed

**Comment by Asnelchristian** [comment]
i am closing it :)
