### ISSUE TITLE
Create a CustomCheckBear for an easy way to write custom static analysis rules to be executed by coala

### ISSUE THREAD

**Issue by underyx** [coala-analyzer/coala-bears#579]
difficulty/high

I think this will be a fairly large proposal with lots of design needed. Right now I'm imagining something like having a `.coachecks/` directory, where users are able to add their own custom check scripts that coala will provide either the source lines and the AST to. These scripts would be run by coala once per file. Here's two examples:

### `.coachecks/usage_of_large_magic_numbers.py`

This checker simply operates on the line strings to find large constant numbers like `seconds = 604800` which would be better written as `seconds = 7 * 24 * 60 * 60`.

```python
import re
from coala import coacheck

for line in coacheck.lines:  # iterator of the lines in one file
    magic_number = re.search(r'(\d{6}\d*)', line).group(1)
    if magic_number:
        if '*' not in line:
            if magic_number.endswith((len(magic_number) - 1) * '0'):
                # replaces `THING = 500000000` with `THING = 5 * 10 ** 8`
                suggested_line = re.sub(r'\d{5}\d*', magic_number[0] + ' * 10 ** ' + str(len(magic_number) - 1))
            else:
                suggested_line = None
            raise coacheck.Error(
                "{} is a large number, why not break it down into how it's calculated?".format(magic_number),
                suggested_line=suggested_line
            )
        else:
            raise coacheck.Warning(
                "{} is a large number, maybe you can break it down further?".format(magic_number)
            )
```

### `.coachecks/string_formatting_urls.py`

This checker finds usages of string formatting in URLs via the AST. It would know to use Python grammar either from the file extensions, or a `.coafile` config value.

```python
from coala import coacheck

# I have zero idea how an AST works, so consider this pseudocode

for formatting_case in coacheck.ast.findall('str_format_operator'):
    if '://' in formatting_case.left_side:
        raise coacheck.Error('You are using raw string formatting to build URLs. Use urllib.parse.urlunparse instead.')

for attribute_access in coacheck.ast.findall('attribute_access'):
    if (
        isinstance(attribute_access.left_side, str)
        and '://' in attribute_access.left_side
        and attribute_access.right_side.identifier == 'format'
    ):
        raise coacheck.Error('You are using raw string formatting to build URLs. Use urllib.parse.urlunparse instead.')
```

**Comment by sils1297** [comment]
Some kind of rules? Your first example isn't particularly simpler than just writing a bear, right? See also: https://github.com/coala-analyzer/coAST/blob/master/ideas.md

**Comment by underyx** [comment]
I do consider it simpler, actually. Not because of the bear API itself, but because of the process of getting that bear to run. In this case, you could just write these few lines, drop it in a project, and have it run automagically. I'm actually not 100% sure about the process of using a custom bear, but I'm sure it's not this simple.

**Comment by sils1297** [comment]
for a custom bear you just write

```python
class Bear(LocalBear):
    def run(filename, file):
        for line in file:
            if re.match(...):
                self.new_result("Message", filename)
```

You can easily put it in your project directory and give coala a `bear_dirs = .` setting in the coafile, then use it as if it's an official one.

**Comment by sils1297** [comment]
see also http://coala.readthedocs.io/en/latest/Users/Tutorials/Writing_Bears.html#a-hello-world-bear

coala bears are made to be simple and also so you can easily add some custom ones for your own project. If they don't suit that purpose we should improve them IMO.

I'm not a fan of running the code on module level like in your mockup, at least a decorated function should be there (which will probably be possible with the next gen bears, the decorator then generates the class).

**Comment by underyx** [comment]
@sils1297 wow, I had absolutely no idea that the `bear_dirs` variable existed. Would it be possible to default it to check `./.coabears/` as well by default? Just to reduce friction even further.

For the record, the API design in my issue description was not really well thought out at all, I just wanted it to be as simple as possible to demo how this would even work. But as it turns out it's already possible :tada:

**Comment by sils1297** [comment]
Hm, guess we could do that. I feel like the main issue here is that you didn't know this before - which is because it's in the developer docs and as a user you don't care about those. So where in the docs do we want to mention this?

It is possible to default the setting this way but I'm not sure we want that, it's somewhat weird and needs some actual code. You can set system wide settings in the default_coafile in the coala installation and user wide in `~/.coarc`, the former is shipped with coala. However paths will always interpreted relative to the directory where they come from :P

**Comment by underyx** [comment]
>You can set system wide settings in the default_coafile in the coala installation and user wide in ~/.coarc, the former is shipped with coala. However paths will always interpreted relative to the directory where they come from :P

The global settings are not really an alternative, since if someone else or CI cloned my project, it wouldn't pick up on the custom checks unless the settings are in .coafile as well.

>It is possible to default the setting this way but I'm not sure we want that, it's somewhat weird and needs some actual code.

Could you elaborate on this? I'm not sure what you mean by 'actual code'. The way I see it we could just add it as a default setting, and make sure that the collector just skips directories that do not exist.

**Comment by underyx** [comment]
As discussed above and on gitter, all this can be accomplished with two other, smaller issues, https://github.com/coala-analyzer/coala/issues/2450 and https://github.com/coala-analyzer/coala/issues/2451

Closing this one.
