### ISSUE TITLE
PyImportSortBear: Blank lines break output

### ISSUE THREAD

**Issue by underyx** [coala-analyzer/coala-bears#583]
type/bug

See this output:
```
setup.py
|   3| import•io

setup.py
|   5|
|    | [NORMAL] PyImportSortBear:
|    | Imports can be sorted.

flask_redis.py
|  11| class•FlaskRedis(object):
|    | [NORMAL] PEP8Bear:
|    | The code does not comply to PEP8.

test_flask_redis.py
|   6| import•flask

test_flask_redis.py
|   8| from•flask_redis•import•FlaskRedis
|    | [NORMAL] PyImportSortBear:
|    | Imports can be sorted.

test_flask_redis.py
|  63| ••••class•FakeProvider(object):
|    | [NORMAL] PEP8Bear:
|    | The code does not comply to PEP8.
```

**Comment by sils1297** [comment]
how is it messed up?

**Comment by underyx** [comment]
Sorry if it wasn't clear @sils1297, instead of

```
test_flask_redis.py
|   6| import•flask

test_flask_redis.py
|   8| from•flask_redis•import•FlaskRedis
|    | [NORMAL] PyImportSortBear:
|    | Imports can be sorted.
```
I thought it should be
```
test_flask_redis.py
|   6| import•flask
|   7|
|   8| from•flask_redis•import•FlaskRedis
|    | [NORMAL] PyImportSortBear:
|    | Imports can be sorted.
```

Now that I think about it might be just an issue with how coala-analyzer/coala handles blank lines in the output.

**Comment by sils1297** [comment]
Hey, the bear specifies which lines are related to the import. Apparently the bear gave line 6 and line 8 (not line 6 to 8!) to coala because the diff touches those. The blank line is not intended to be shown here.

**Comment by underyx** [comment]
Oh, that's my bad then. Either way, I find this pretty hard to skim/visually parse. Definitely a coala issue though, so continuing the discussion at https://github.com/coala-analyzer/coala/issues/2458
