### ISSUE TITLE
[ESLint] Empty files does not work as expected

### ISSUE THREAD

**Issue by RaitoBezarius** [coala-analyzer/coala-bears#593]
Steps to reproduce:

1. Create an empty JavaScript file.
2. Run the ESLint bear on it.
3. Get a `json.loads` exception and lose the monopoly.

Why does it happens?

We are using the `--stdin` option to pass the file content, but we might be assuming the file content is non-empty, following is that `eslint` does not return any JSON. We just have a `()` (empty tuple) as file.

**Comment by RaitoBezarius** [comment]
Refer to #594 for a fix.

**Comment by AbdealiJK** [comment]
Fixed in https://github.com/coala-analyzer/coala-bears/pull/594
