### ISSUE TITLE
generate_package: Test the version variable

### ISSUE THREAD

**Issue by Adrianzatreanu** [coala-analyzer/coala-bears#597]
Currently it has a pragma no cover as the testing should be done with mocking probably, so those should be removed.

``            if 'dev' in bear_version:  # pragma: no cover ``

``                  bear_version = bear_version[:bear_version.find("dev")] + ( 
                     nano_version)``
``
              else:  # pragma: no cover
``

**Comment by tushar-rishav** [comment]
I think you may be able to mock the version by containing it within an object (dict) and then mocking that object. Something like:
```python
from unittest.mock import patch
from coalib import VERSION

version_dict = {'v':VERSION}
print(version_dict) # Original version
with patch.dict(version_dict, v=458):
    print(version_dict['v'])  # Mocked version now do whatever

print(version_dict) # Original version again

```
CC @Adrianzatreanu

**Comment by chriscoyfish** [comment]
I can work on this issue

**Comment by Adrianzatreanu** [comment]
All yours!
