### ISSUE TITLE
bears/ShellCheckBear: severity_map missing

### ISSUE THREAD

**Issue by mr-karan** [coala-analyzer/coala-bears#598]
Need to add that ^

**Comment by Makman2** [comment]
why? does ShellCheck output severities we don't support by default?

**Comment by mr-karan** [comment]
@Makman about this, I have a question. Don't we need to map the regex group to the severity_map and only then the highlighted colors will show up? 

So according to me 
severity_map={'info':RESULT_SEVERITY.INFO} will highlight that regex output with the specific color?

**Comment by Makman2** [comment]
What colors? The severity map is just there for mapping the textual severity value to an enum value. `@linter` provides a default map.

**Comment by mr-karan** [comment]
@Makman2 See this https://github.com/coala-analyzer/coala/blob/master/coalib/results/RESULT_SEVERITY.py#L5

`green`,`yellow`,`'red` are mapped based on that enum value right? What is the default map?

**Comment by Makman2** [comment]
current supported severity map:
```
severity_map=MappingProxyType({
                    "critical": RESULT_SEVERITY.MAJOR,
                    "c": RESULT_SEVERITY.MAJOR,
                    "fatal": RESULT_SEVERITY.MAJOR,
                    "fail": RESULT_SEVERITY.MAJOR,
                    "f": RESULT_SEVERITY.MAJOR,
                    "error": RESULT_SEVERITY.MAJOR,
                    "err": RESULT_SEVERITY.MAJOR,
                    "e": RESULT_SEVERITY.MAJOR,
                    "warning": RESULT_SEVERITY.NORMAL,
                    "warn": RESULT_SEVERITY.NORMAL,
                    "w": RESULT_SEVERITY.NORMAL,
                    "information": RESULT_SEVERITY.INFO,
                    "info": RESULT_SEVERITY.INFO,
                    "i": RESULT_SEVERITY.INFO,
                    "suggestion": RESULT_SEVERITY.INFO}),
```
the color mappings are performed by the result, you don't have to care as a linter-bear-writer about that^^

**Comment by mr-karan** [comment]
alright thanks for clarification, closing it
