### ISSUE TITLE
PEP8Bear for Jupyter Notebooks

### ISSUE THREAD

**Issue by caichinger** [coala-analyzer/coala-bears#605]
Jupyter Notebooks are widely used for tutorials.

It would therefore be nice to have PEP8Bear for notebooks to make sure basic code style standards are met.

I will give this a try and join your sprint later. ;)

**Comment by sils1297** [comment]
Neat, see you!

**Comment by sils1297** [comment]
We could also add grammar checking for the other parts with languagetool :)

**Comment by sils1297** [comment]
CC @Udayan12167 and @mr-karan this is the first bear we'd have that should reuse other bears for parts of the file with different languages. We should think of this as a potential new concept, just write a bear for that particular file and that bear then could deal with invoking the others for the parts?

**Comment by caichinger** [comment]
I started working on this issue and the current draft can be found here:
https://github.com/caichinger/coala-bears/tree/605_ipynb_pep8bear

Currently I am on holidays but I will continue when I come back at beginning of August.

Some thoughts:
- Reading/writing Jupyter Notebooks most easily done with https://github.com/jupyter/nbformat (no problem with different versions, etc.). Everybody working with Jupyter automatically has this lib installed. Is nbformat a feasible requirement?
- The Notebook related part is independent of the bear (it could e.g. be a Julia-Notebook). Where is a good place for the Notebook-part?
- At the moment I encounter problems when supplying the test files as plain strings (due to \n). I will take a look at this.
- When I come back I will prepare a PR for easier reviewing.

**Comment by Makman2** [comment]
Nice thx @caichinger ! cool you are working on this :)
We will send out an invitation to our org, then you can be assigned to this issue so no one starts doing redundant work :+1:

**Comment by Makman2** [comment]
for help, conversion whatsoever feel free to drop by at our gitter channel: https://gitter.im/coala-analyzer/coala

there we can help you too with proceeding on this issue :+1: :smile:

**Comment by sils1297** [comment]
Hi! Welcome to our community and thank you for your interest!

I have sent you an invitation to join our community. This is needed so we can coordinate tasks with you and make sure no two persons are working on the same thing. If you can't find the mail, you should be able to join us at http://github.com/coala-analyzer/!

We'd love to be able to help you when problems occur. Just join us on [our gitter channel](https://gitter.im/coala-analyzer/coala) and tell us about them :)

**Comment by sils1297** [comment]
@Makman2 feel free to send out invitations on your own.

**Comment by sils1297** [comment]
@caichinger assigning you as you have a WIP PR in the works. Ping us if you want us to unassign you.

**Comment by caichinger** [comment]
@sils1297 "Ping us if you want us to unassign you" - Thx, I will let you know!
