### ISSUE TITLE
README: Make the list of languages more editable somehow

### ISSUE THREAD

**Issue by hypothesist** [coala-analyzer/coala-bears#616]
Maybe generate them automatically?

**Comment by mr-karan** [comment]
from `coala-json`, you can.

**Comment by AbdealiJK** [comment]
The script is fairly small and can be easily written in a few minutes ...
It cannot be auto updated in the readme file as reST does not support any dynamic methods, and the PyPI version of rST is even more restrictive.
Also, it makes sense for the person who is writing the release notes to do it.


PS: Here's a quick script based on @mr-karan 's idea
```
import json, subprocess

str_data = subprocess.check_output(["coala-json", "--show-bears"])
data = json.loads(str_data.decode('utf-8'))
print(set(l for bear in data["bears"] for l in bear["LANGUAGES"]))
```
