### ISSUE TITLE
script to count Bears

### ISSUE THREAD

**Issue by abhsag24** [coala-analyzer/coala-bears#618]
so right now we manually mention Bears on our Readme, it'd be cool to have a bear that can count the bears and generate a cool badge!

**Comment by hypothesist** [comment]
I'm not sure if this should be a bear. I think a simple script will suffice.

**Comment by sils1297** [comment]
IMO a script will do

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
http://coala-analyzer.org/ - http://viperdev.io/ - http://gitmate.com/

**Comment by Makman2** [comment]
script :P

**Comment by AbdealiJK** [comment]
I think there are already a LOT of scripts to do these sort of things:
 - List of bears: `find . -name "*Bear.py"`
 - List of bears sorted based on module name (i.e. sorted based on language) - `find . -name "*Bear.py" | sort`
 - Number of bears - `find . -name "*Bear.py" | wc -l`

**Comment by hypothesist** [comment]
Or `coala -B | wc -l`

**Comment by AbdealiJK** [comment]
`coala -B | wc -i` is so much easier ^_^

Closing this then
