### ISSUE TITLE
awk linting using `gawk --lint`

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala-bears#62]

**Comment by AbdealiJK** [comment]
Do people actually write complete programs using awk ? I thought it's only used intermittently in bash programs.
If we don't have an awk specific file - this wouldn't be useful, as there wont be any file we can use it on

**Comment by AbdealiJK** [comment]
Assigning @SanketDG as he's working on it

**Comment by Makman2** [comment]
awk has some weird syntax and I was told it's not used that often any more. Also you normally use a few search statements embedded inside scripts, what makes the extraction quite difficult. Not worth the effort for a few lines of linting (for us and the one who needs to extract the actual awk expressions).

Accepting patches.
