### ISSUE TITLE
Modify .gitignore to reflect this repo

### ISSUE THREAD

**Issue by SanketDG** [coala-analyzer/coala-bears#65]
Remove redundant things and modify things that were `coala` specific to `coala-bears` specific

**Comment by sils1297** [comment]
anything specific?

**Comment by SanketDG** [comment]
`coala.egg_info` should be `coala_bears.egg-info`. In general, it should be `*.egg_info/`

`coala.1`, `org.coala_analyzer.v1.service` should be removed.

This should also be done for the `coala` repository for bear specific things.

**Comment by Adrianzatreanu** [comment]
I think this fixed what you asked for, and i referenced a commit to this issue :)
