### ISSUE TITLE
InvalidLinkBear xmlns retrieval fail is not actually a fail

### ISSUE THREAD

**Issue by maweki** [coala-analyzer/coala-bears#689]
The InvalidLinkBear should not try to retrieve any xml namespace uris.

The documentation *clearly* states: "The namespace name, to serve its intended purpose, SHOULD have the characteristics of *uniqueness* and *persistence*. It is **not a goal that it be directly usable for retrieval** of a schema (if any exists)."

https://www.w3.org/TR/REC-xml-names/#ns-decl

**Comment by sils1297** [comment]
CC @SanketDG

**Comment by maweki** [comment]
`<img src="//domain.com/img/logo.png">`

This should try to both retrieve https://domain.com/img/logo.png and http://domain.com/img/logo.png. If either is valid then this should be ok. If both are invalid this would be a fail. It needs to be checked and it currently isn't.

**Comment by sils1297** [comment]
closing in favour of https://github.com/coala-analyzer/coala-bears/issues/691

**Comment by maweki** [comment]
(?<!xmlns(:(\w|\d)+)?=(\"|\')?)
