### ISSUE TITLE
QuotesBear: Use the same type of quotes

### ISSUE THREAD

**Issue by hypothesist** [coala-analyzer/coala-bears#697]
For example  `Constants.py` has both `'string'` and `"string"`.

We have the quotes data for each language available in coalang IIRC. CC @abhsag24

**Comment by hypothesist** [comment]
Feel free to change the name :P

**Comment by sils1297** [comment]
note that the algorithm should e.g. allow single quotes if double quotes
are within the string. I think this might be difficulty low or so even as
we already have a bear that finds out what are strings and what not huh/

**Comment by abhsag24** [comment]
so AnnotationBear can get rid of the problem that @sils1297 had other then that it shouldn't be that hard?

**Comment by AbdealiJK** [comment]
Closing in favor of https://github.com/coala-analyzer/coala-bears/issues/557 which has more discussion about this
