### ISSUE TITLE
Better error messages on test fail

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala-bears#72]
All LocalBearTestHelpers based classes have horrible test messages. Earlier we had caught the case when the bear's output is None, and printed that it was none with the bear's message queue. But now, with the `Lint` class, we would love to have the `command`, `stdout_output`, and `stderr_output` shown even if the bear did not return None (as we need to see what command was executed.)

 1. I suggest we show the message queue on any error type. (A little excess information ... but it doesn't hurt - especially after the hefty debugging required in haskell and R cases)
 2. Use LOG_LEVEL = DEBUG in `verify_local_bear`. This functions makes debugging impossible as the traceback is useless. So, it's better to get all debug information from the Bear itself in this case.
 3. Add a `self.debug()` to the Lint class. This along with (2) will provide awesome debugging information for the Lint class.

**Comment by sils1297** [comment]
neat!

2016-02-22 3:12 GMT+01:00 AbdealiJK <notifications@github.com>:
