### ISSUE TITLE
Usage of DistributionRequirement

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala-bears#720]
It seems like the docs of DistributionRequirement state, to use it you need to do: `dr = DistributionRequirement(apt_get='libclang', dnf='libclangg')` but in all our bears, ike GNUIndentBear, we use `REQUIREMENTS = {DistributionRequirement(apt='indent')}`
Is it apt ? or apt-get ?

Note that in Ubuntu 16.04+ it isrecommended to use `apt install indent` while lower recommends `apt-get install indent`

CC @Adrianzatreanu

**Comment by Adrianzatreanu** [comment]
Thats actually something I didnt notice, ill take a look soon :)

**Comment by Makman2** [comment]
on Ubuntu 16 `apt-get` is now `apt`. I don't know if `apt-get` is still available, but we should either duplicate the repo entries for `apt` and `apt-get` or code a reroute depending on which Ubuntu is used^^

@Adrianzatreanu

**Comment by Adrianzatreanu** [comment]
i think apt-get works on ubuntu 16.04 too but is recommended not to be used. i think its fine to leave it like this :) unless we receive complaints.

**Comment by Makman2** [comment]
alright :+1: :)
