### ISSUE TITLE
CPDBear: Increase minimum tokens default to 30

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala-bears#735]
I think we should rather have a lower false positive rate by default even.

difficulty/newcomer

**Comment by Makman2** [comment]
from @ku3o
> After a discussion, we decided not to change minimum-tokens value as a fix of the bug should increase report readability and communicate potential false positive cases better.

Closing this.

**Comment by Makman2** [comment]
See https://github.com/coala-analyzer/coala-bears/pull/805
