### ISSUE TITLE
JSHintBear can't be used with use_es6_syntax=True

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala-bears#740]
`Incompatible values for the 'esversion' and 'esnext' linting options. (0% scanned).`

type/bug

**Comment by sils1297** [comment]
apparently I have to set es_version as well!? I' think we want to remove the use_es6_syntax setting or symlink it or so for backwards compatability

**Comment by sils1297** [comment]
this can be worked around by not using `use_es6_syntax = true` and instead using `es_version = 6`

**Comment by AbdealiJK** [comment]
Looking at the JSHint docs, it also says that the `esnext` (what we call `use_es6_syntax`) is deprecated.
```
Warning This option has been deprecated and will be removed in the next major release of JSHint. Use esversion: 6 instead.
```
`esversion` is our `es_version`

So, removing this argument all together is what is needed.

**Comment by sils1297** [comment]
I think we should translate it to es_version for backwards compatability
