### ISSUE TITLE
InvalidLinkBear: `ignore_regex` option name is too generic

### ISSUE THREAD

**Issue by underyx** [coala-analyzer/coala-bears#746]
Difficult to tell in `.coafile` what this option means, and name clashes with other bears are possible.

**Comment by AbdealiJK** [comment]
I think this is a newcomer issue if we can figure out what to name it.
Is `ignore_link_regex` a fine name ? Any other suggestions ?

**Comment by underyx** [comment]
`link_ignore_regex`?

**Comment by Makman2** [comment]
I like both :3

**Comment by meetmangukiya** [comment]
I would like to be assigned this issue.
