### ISSUE TITLE
GitCommitBear - displays "HEAD commit has no message" though there is one

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala-bears#75]
Very few people are able to understand the current messages.
We should make it simpler.

**Comment by sils1297** [comment]
Something like this?

HEAD Commit has no message -> HEAD commit message lacks a body

**Comment by Makman2** [comment]
Wait this is actually wrong, `HEAD commit has no message` means the commits message is really empty!

**Comment by sils1297** [comment]
@Makman2 please get to the bottom of this, this is apparently no newcomer bug but an actual issue that needs investigation.

**Comment by Makman2** [comment]
See https://circleci.com/gh/coala-analyzer/coala-bears/120

**Comment by AbdealiJK** [comment]
The link youve given says the commit has long lines ?

**Comment by Makman2** [comment]
oh yeah this is the wrong one :O thanks
but then I can't find the old one any more where it says "No commit message" ...

**Comment by Makman2** [comment]
Ah found!
https://circleci.com/gh/coala-analyzer/coala-bears/109
for commit https://github.com/coala-analyzer/coala-bears/commit/3cb17432361df8b6db9f820c9edd06c089b4efd6

**Comment by sils1297** [comment]
@Makman2 did you manage to find out what's wrong here yet?

**Comment by Makman2** [comment]
not yet, I think we should postpone this issue^^
