### ISSUE TITLE
coala-bears updates setuptools

### ISSUE THREAD

**Issue by underyx** [coala-analyzer/coala-bears#751]
I don't think it's nice to change people's setuptools versions. This can potentially break entire systems.

**Comment by sils1297** [comment]
agree, did you install with `-U`? What should we do instead?

**Comment by underyx** [comment]
I did install with `-U`, yep, just realized that. Regardless, that's still no reason to change system packages. I think it's reasonable to assume that the system already has setuptools and remove it, especially since we don't even support old Python versions. Is there any reason it needs to be there?

**Comment by sils1297** [comment]
well with -U pip upgrades everything thats speced

**Comment by sils1297** [comment]
we require setuptools

**Comment by underyx** [comment]
I know why it happened 💃

If I want to upgrade coala-bears from 0.8 to 0.9, I still wouldn't want it to break my system. I'm saying, maybe we could also just assume that setuptools is installed _everywhere_.

**Comment by AbdealiJK** [comment]
Btw, the setuptools in requirements.txt doesn't do much for us from what I understand because we import setuptools before we parse and give that requirement to pip.
Some testing would be good to check this though - maybe pip does some special handling

PS: We also have mentioned `setuptools>=19.2` which is pretty high. setuptools v1.x is what was there in ubuntu-precise IIRC (which is still officially supported until next year)

**Comment by AbdealiJK** [comment]
Apparently pip now throws an error if you do a source installation without setuptools asking you to install it.
https://github.com/pypa/pip/blob/3417fac05e48fff50497e07566ecaeb143065f02/pip/req/req_install.py#L382

**Comment by underyx** [comment]
>we could also just assume that setuptools is installed *everywhere*, and perhaps document the need for it.

@AbdealiJK This is still my suggestion, which doesn't conflict with that fact.

**Comment by AbdealiJK** [comment]
@underyx I know, I'm for it :) Just giving more proof.
I am still wondering whether whether adding setuptools in requirements.txt actually does anything. Because that file is only read after setuptools is imported.
