### ISSUE TITLE
KeywordBear settings are weirdly named

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala-bears#756]
cs_keywords and ci_keywords are pretty bad names and that isn't user friendly. We should deprecate that for something better.

**Comment by AbdealiJK** [comment]
If we can decide on a name, this can become a newcomer issue. What about `keywords_case_insensitive`, `keywords_case_sensitive` ?

**Comment by Makman2** [comment]
maybe we want to use `keywords_case_insensitive` only? can't imagine a case where a keyword needs to be case sensitive^^ Then there's only a single setting which could just be called `keywords`^^

**Comment by sils1297** [comment]
agree with makman

**Comment by Makman2** [comment]
So imo this issue is not closed yet as I thought we ag eed on just having a single `keywords` setting which checks up on keywords always case-insensitively?

**Comment by Makman2** [comment]
wait nvm I'll open another issue^^

**Comment by Makman2** [comment]
See https://github.com/coala-analyzer/coala-bears/issues/782
