### ISSUE TITLE
circleci caching doesn't work?`

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala-bears#769]
it tells `circle.yml specified cache directory: /home/ubuntu/.local/share/coala-bears but it does not exist` :/ that should cache away the checkstyle issue

**Comment by sils1297** [comment]
CC @underyx

**Comment by underyx** [comment]
:point_right: [September 6, 2016 1:30 AM](https://gitter.im/coala-analyzer/coala?at=57ce002ecdbf820f7f9de210)
