### ISSUE TITLE
Codecov doesn't have reports on master

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala-bears#77]
I sent out a support request:

> I've got a report at https://codecov.io/github/coala-analyzer/coala-bears?ref=3c2e81d5771c4c39da9c05bca18d6869ad5479d6 which already admits that this is a valid one for our master branch, but on https://codecov.io/github/coala-analyzer/coala-bears it just says "No reports found for master." I think this is a problem on your side.

> report's uploaded at https://circleci.com/gh/coala-analyzer/coala-bears/72

Awaiting response.

**Comment by sils1297** [comment]
CC stevepeak , assuming this is a codecov problem.

**Comment by sils1297** [comment]
@stevepeak

**Comment by stevepeak** [comment]
Not sure why caused this issue... but the database trigger did not create a branch record for master, which is super odd. I manually added the branch so now reports are visible on master.

Thanks!

**Comment by sils1297** [comment]
@tushar-rishav can you confirm that and make a newcomer bug?

**Comment by sils1297** [comment]
@stevepeak thanks for the fast response!

**Comment by stevepeak** [comment]
@sils1297 I'm reviewing the db code now. Its very straight forward, confused why this happened. Thanks for pinging me on this :+1:

**Comment by sils1297** [comment]
Sure!

@stevepeak so https://codecov.io/github/coala-analyzer/coala-bears is not our master report, it may be the one I pointed you to because that was the master at that time but we'd rather have the current one... will it update correctly on the next fastforward?

**Comment by sils1297** [comment]
/me has a PR to merge actually :) https://github.com/coala-analyzer/coala-bears/pull/78

**Comment by stevepeak** [comment]
It should update when the next commit comes through. Can you ping when when you submit one? I'll check back shortly to verify. Thanks!

**Comment by sils1297** [comment]
PR merged, build queued at https://circleci.com/gh/coala-analyzer/coala-bears/102 , done in approx. 5 minutes I guess.

**Comment by sils1297** [comment]
From slack

@stevepeak so the master sync doesn't seem to work: https://circleci.com/gh/coala-analyzer/coala-bears/102
I get the right report on https://codecov.io/github/coala-analyzer/coala-bears?ref=a435c7a8df1e7728ccfca7e5fdc80de3b393842e but not on https://codecov.io/github/coala-analyzer/coala-bear

**Comment by sils1297** [comment]
ok we consider this solved, assuming it'll update in the future.
