### ISSUE TITLE
Add codecov badge to README.rst

### ISSUE THREAD

**Issue by tushar-rishav** [coala-analyzer/coala-bears#80]
[codecov](http://shields.io/) badge is missing from `README.rst` . Add a badge with [https://codecov.io/github/coala-analyzer/coala-bears](https://codecov.io/github/coala-analyzer/coala-bears) as target.

**Comment by sils1297** [comment]
just as in the readme for the coala repo

**Comment by siddhanjay** [comment]
As I am new here , can I take up this issue ?

**Comment by sils1297** [comment]
@siddhanjay I've invited you to the org, please accept and confirm, then I can assign you.

**Comment by siddhanjay** [comment]
@sils1297 I have accepted the invitation

**Comment by sils1297** [comment]
@siddhanjay awesome - it's yours! Welcome :) You can get help at https://gitter.im/coala-analyzer/coala
