### ISSUE TITLE
ClangComplexityBear

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala-bears#81]
should be easy to use the clang ast to calculate cyclomatic complexity

**Comment by Redridge** [comment]
How do you get the clang ast?

**Comment by sils1297** [comment]
look at ClangASTPrintBear for sample code on iterating over the clang ast.

**Comment by Redridge** [comment]
Should this be able to suggest ways to reduce the cyclomatic complexity? If not I would like to give it a try.

**Comment by sils1297** [comment]
not for now, would be neat to have a general markdown tutorial in the debug
message of the result or so

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-02-23 16:52 GMT+01:00 Alexandros Dimos <notifications@github.com>:

**Comment by Uran198** [comment]
@Redridge Are you still working on this or can I try to do it?

**Comment by Redridge** [comment]
@Uran198 you have my blessing

**Comment by Uran198** [comment]
OK, so the approach here would be to calculate it for each module and display it. But, as for the general markdown tutorial, what should it contain? Something about, that recommended number is 10 and when it is higher there have to be a good reason for it?

**Comment by sils1297** [comment]
yeah calculate the complexity and let the user specify one (or several for minor, normal, major) threshold(s)
